Feature/oop autoloading
iurciuc/passman pull request #2
Opened 2024-12-14 14:15 UTC by iurciuc

2024-12-14 18:50 UTC, aharabara requested changes

2024-12-14 18:50 UTC, aharabara commented on autoloader.php
> +    if (strncmp($prefix, $class, $len) !== 0) {
str_starts_with?

2024-12-14 18:50 UTC, aharabara commented on index.php
> +exit((new Application(new PasswordsFileService(new FileEncryptorService()), new Router()))->run());
😅 начинает попахивать необходимостью использовать контейнер

2024-12-14 18:50 UTC, aharabara commented on src/Actions/AddNewRecordAction.php
> +        echo 'Password added'.PHP_EOL;
Echo плохо - вытащить в сервис формата IO как минимум. Туда же confirm/choose/input

2024-12-14 18:50 UTC, aharabara commented on src/Actions/AddNewRecordAction.php
> +        echo 'Password added'.PHP_EOL;
redline только из IO .

2025-01-29 18:10 UTC, iurciuc commented on src/Actions/AddNewRecordAction.php
> +        echo 'Password added'.PHP_EOL;
confirm/choose/input будет чуть позже

2025-01-29 18:10 UTC, merged